### PR TITLE
maintain: remove some unused server options

### PR DESCRIPTION
**Pull request by dnephin**
This PR removes some unused `loadCertificate` logic and options from the server. We may restore this in the future when it is being used. For now I think it's better to remove it so that contributors are not distracted by it. Removing it also avoids doing unnecessary work on server startup.

This PR also moves one test file into the `pki` package. It was only testing things in that package.  The `pki` package is also not used, but at least it's well contained and is not called by any production code.

### CODE REVIEW

**Comment by BruceMacD** [comment]
Any way we can capture this commit in an issue for loading certificates in Infra? It seems like an option we will want soon and I'd like an easy way to find this existing work.

**Review by ssoroka — CHANGES_REQUESTED** [review]
It wasn't too long ago that I resolved the issue that asked for the ability to load user-specified certs. Seems like a step backwards. cc @jmorganca to decide how to move forward.

**Comment by dnephin** [comment]
Good call to create an issue about this. I was thinking of adding support for that next. I've created #2176 to track it.

I'm not really sure how this code being removed relates to users being able to specify their own cert and key. Supporting that should be really simple, just creating a `tls.Config` out of the config they provided. I suspect we won't use any of what is being removed here to support #2176.

**Comment by ssoroka** [comment]
Ah, sorry, this is the certificate provider stuff. This is related to the plan that we will manage certificate rotation for the user. Can't say I'm excited to see it go away.

**Comment by dnephin** [comment]
Git makes it easy to restore it back later. Is there an issue related to that feature? I can put a note into that issue to link back to this PR, so we can find it easily.

**Review by ssoroka — APPROVED** [review]
discussed concerns. good to go.

**Comment by dnephin** [comment]
Thank you!

**Pull request merged**
