### PR TITLE
fix: migrate destination request CA from string

### LINKED ISSUE #2200: connector: error when using 0.13.1 with `main`
When using Connector on `main` with Infra Server on `0.13.1`:

```
{"level":"error","ts":1654277753.9561458,"caller":"connector/connector.go:525","msg":"initializing destination: error creating destination: bad request: illegal base64 data at input byte 0"}
```

### PR DESCRIPTION
**Pull request by BruceMacD**
## Summary
When using a connector on versions `0.13.1` and earlier they were unable to parse the CA response on destination requests as they were expecting a string. This PR adds migrations to convert the CA on destination request/responses for `0.13.1` and below.

## Checklist

- [ ] Wrote appropriate unit tests
- [x] Considered security implications of the change
- [x] Updated associated docs where necessary
- [x] Updated associated configuration where necessary
- [x] Change is backwards compatible if it needs to be (user can upgrade without manual steps?)
- [x] Nothing sensitive logged
- [x] Considered data migrations for smooth upgrades

## Related Issues

Resolves #2200

### CODE REVIEW

**Review by dnephin — COMMENTED** [review]
Could you add a test case that fails without this migration? I guess we have a way to reproduce it, right?

**Review by ssoroka — APPROVED** [review]
Ok I understand what's going on. relevant playground: https://go.dev/play/p/I_zKy4KKZeQ
[]byte and string aren't json encoded the same way. []byte is base64 encoded, and this migration fixes it by converting the encoding type properly.

**Review by dnephin — CHANGES_REQUESTED** [review]
We should at the very least have a test for this before merging.

But I think given what we've learned, we should also reconsider using `[]byte` for this. A pem encoded cert is already base64 encoded.

I think another approach would be use to a `type PEMstring string` and make it so that the automatic trimming does not apply to custom types.

We can add a `UnmarshalText` to `PEMstring` to do the correct normalization.

**Comment by dnephin** [comment]
I put together an example of that here: #2217, but it still needs more tests

**Comment by ssoroka** [comment]
I've forgotten why I changed it to []byte already, but perhaps we should consider changing the API back to a string field for this.

**Comment by dnephin** [comment]
I believe PEM encoded strings are supposed to have a single trailing newline, so we wanted to avoid removing it.

**Comment by BruceMacD** [comment]
Closed in favor of #2217

**Pull request closed without merging**
