### PR TITLE
improve: add codeql code analysis

### PR DESCRIPTION
**Pull request by mxyng**
## Summary

Add codeql to pull requests so we get early feedback on code changes. Can be replaced at any time with other static analysis tools. Analysis will run in the release pull request and will need to pass in order to merge the PR and release. 

Refactored pull request actions into separate files: 
- `pull_request.yml` for common actions
- `release_pull_request.yml` for release-only actions
- `human_pull_request.yml` for human-created pull requests, i.e. not `dependabot`.

### CODE REVIEW

**Comment by ssoroka** [comment]
looks like we need to ignore generated js files, but otherwise good?

**Comment by mxyng** [comment]
This is the first pass so will definitely need to update configurations

**Comment by mxyng** [comment]
Add `paths-ignore` to ignore generate JS files

**Review by dnephin — APPROVED** [review]
LGTM!

**Pull request merged**
