### PR TITLE
fix issue with "unknown user" message

### PR DESCRIPTION
**Pull request by ssoroka**
## Checklist

- [ ] Wrote appropriate unit tests
- [ ] Considered security implications of the change
- [ ] Updated associated docs where necessary
- [ ] Updated associated configuration where necessary
- [ ] Change is backwards compatible if it needs to be (user can upgrade without manual steps?)
- [ ] Nothing sensitive logged
- [ ] Considered data migrations for smooth upgrades

## Related Issues

Resolves #

### CODE REVIEW

**Comment by dnephin** [comment]
> We remove the grants if the last user provider & placeholder(models.Identity) is removed.

I believe we already do that here: https://github.com/infrahq/infra/blob/5fd5af7640645a888b135582f8581bf86512c7d0/internal/server/data/identity.go#L674-L685

I guess it's always possible that a user is removed after the first API call to list grants, but before the next API call to list users.

Maybe we should use the userID in the list output if we can't lookup the user name?

**Comment by ssoroka** [comment]
I think most people on the team have run into this, so it's not a race condition. it's possible that it's from before we were deleting grants–I'm not sure how old that code is–but we should probably still handle this somehow if we're already deleting them and people are still managing to hit this scenario. Ignoring the record does seem to make some sense, as it's a grant that doesn't have an associated user/group, which is worthless.

**Comment by dnephin** [comment]
If the problem is inconsistent data, I think we should clean that up instead of trying to patch it in the CLI. Hiding things from output, especially things that are related to access control, seems like a risky approach. It could mislead someone looking at the output to believe access doesn't exist, or make it harder for us to find other bugs in the future because they are being masked by this change.

**Comment by ssoroka** [comment]
It's not really a race. Definitely #1382 will help, but you'll have the same problem: some grants won't join to user records because they're simply not there.

**Review by BruceMacD — APPROVED** [review]

**Pull request merged**
