### PR TITLE
fix: client requests should time out

### PR DESCRIPTION
**Pull request by ssoroka**
Resolves https://github.com/infrahq/infra/issues/1965

### CODE REVIEW

**Review by pdevine — COMMENTED** [review]
This seems OK, but the error is probably not going to be great for the user. We should trap the error and return a reasonable response saying that the client timed out waiting for the infra server.

**Comment by ssoroka** [comment]
I think there's multiple types of networking errors that can happen, and it's possibly somewhat os-dependent. it'd be [hard to catch them all](https://stackoverflow.com/questions/22761562/portable-way-to-detect-different-kinds-of-network-error) and have a reasonable message that doesn't assume too much.

**Comment by dnephin** [comment]
We don't need to catch them all. I think there's only two places where this can timeout:
1. in the call to `http.Client.Do`
2. reading the `response.Body`

`http.Client.Do` says:

> // Any returned error will be of type *url.Error. The url.Error
> // value's Timeout method will report true if the request timed out.

That makes it pretty easy to check for a timeout on that call.

The error from reading `response.Body` is likely less easy, but also likely less common. A check for `io.EOF` or `errors.Is(err, context.DeadlineExceeded)` would probably be reliable enough for this.

**Review by dnephin — APPROVED** [review]
LGTM

**Review by pdevine — APPROVED** [review]

**Pull request merged**
